GET http://localhost:3000/classes/mine?testUserId=6173ca66fb1a493f54ec8968

###

POST http://localhost:3000/friends/create-request
Content-Type: application/json

{
  "testUserId": "6173ca66fb1a493f54ec8968",
  "userId": "6173ca34fb1a493f54ec8967"
}

###